services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=123456  # 设置管理员密码
      - xpack.security.enabled=false  # 禁用安全设置，不启用 SSL/TLS
      - xpack.security.transport.ssl.enabled=false  # 禁用集群之间的 SSL
      - xpack.security.http.ssl.enabled=false  # 禁用 HTTP SSL
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
        interval: 30s
        retries: 3
    # 配置资源限制
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=elastic # 由于我禁用了 安全设置，所以这里不用填写  注：8.x 就设置服务账号
      # - ELASTICSEARCH_PASSWORD=123456  # 设置与 Elasticsearch 相同的密码 注：8.x 就设置服务密码
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    # 启动时配置 Kibana 连接 Elasticsearch 的证书和用户名密码

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge
