services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=123456  # 设置管理员密码，账号：elastic
      # - xpack.security.enabled=false  # 禁用安全设置
      - ELASTICSEARCH_HEAP_SIZE=1g
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/elasticsearch-key.pem
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/elasticsearch-cert.pem
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/elasticsearch-cert.pem
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/elasticsearch-key.pem
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/elasticsearch-cert.pem
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/elasticsearch-cert.pem
    volumes:
      # - ./certs:/certs  # 将证书挂载到容器中
      - ./backend/apps/backend/certs:/usr/share/elasticsearch/config/certs
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
        test: ["CMD", "curl", "-f", "https://localhost:9200/_cluster/health"]
        interval: 30s
        retries: 3
    # 配置资源限制
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    # environment:
      # - ELASTICSEARCH_URL=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=kibana_system # 由于我禁用了 安全设置，所以这里不用填写  注：8.x 就设置服务账号
      # - ELASTICSEARCH_PASSWORD="123456" # 设置与 Elasticsearch 相同的密码 注：8.x 就设置服务密码
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD="123456"
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/elasticsearch-cert.pem
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none  # 可选：强验证 full，忽略主机名验证 none，在容器里跑可能得设置为 none
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana-key.pem
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana-cert.pem
    volumes:
      - ./backend/apps/backend/certs:/usr/share/kibana/config/certs
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    # 启动时配置 Kibana 连接 Elasticsearch 的证书和用户名密码

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge
