// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-access';
export { useAntdConfig, useAntdConfigSetter } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-antd';
export { Icon, getIconComponent } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-icons';
export { KeepAliveContext, closeAllTabs, closeTab, dropByCacheKey, useKeepOutlets } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-keepalive';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-locale';
export { Provider, useModel } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-access/types.d';
export * from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-antd/types.d';
export * from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-layout/types.d';
export * from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/apps/frontend/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/node_modules/.pnpm/@umijs+renderer-react@4.4.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/node_modules/.pnpm/@umijs+renderer-react@4.4.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'E:/Code/work/shared/temp/front-end/am-admin/frontend/node_modules/.pnpm/umi@4.4.1_@babel+core@7.26.0_@types+node@18.16.9_@types+react@18.3.1_eslint@8.35.0_jest@29.7._6prusja2is24er2hudpurxywnu/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
